开发debugger框架

diff --git a/unit/interpreter/official_test/Makefile b/unit/interpreter/official_test/Makefile
--- a/unit/interpreter/official_test/Makefile
+++ b/unit/interpreter/official_test/Makefile
@@ -1,4 +1,4 @@
-all: test
+all: test test_my
 
 #../../../bin/jencs test.hdf test.cs
 
@@ -13,6 +13,7 @@ all: test
 #test_crc.cs 不实现
 
 #test_escape.cs 待完善
+#test_setorder.cs 待修正
 CS_TESTS = test.cs test2.cs test3.cs test4.cs test5.cs test6.cs test7.cs \
 			test8.cs test9.cs test10.cs test11.cs test12.cs \
 			test14.cs test15.cs test17.cs test18.cs test19.cs \
@@ -27,7 +28,6 @@ test: $(CS_TESTS)
 	@echo "Running cs regression tests..."
 	@failed=0; \
 	for test in $(CS_TESTS); do \
-		rm -f $$test.out; \
 		echo "Parsing $$test" > $$test.out; \
 		../../../bin/jencs test.hdf $$test >> $$test.out; \
 		diff $$test.out $$test.gold > $$test.diff; \
@@ -36,15 +36,41 @@ test: $(CS_TESTS)
 			echo "Failed Syntax Regression Test(回归测试): $$test"; \
 			echo " See $$test.out and $$test.diff"; \
 			failed=1; \
+		else \
+			rm -f $$test.out; \
+			rm -f $$test.diff; \
 		fi; \
 	done; \
-	echo ""; \
 	if [ $$failed -eq 1 ]; then \
 		echo "Test Failed!"; \
 	else \
-		echo "All Regression Test passed!"; \
-	fi
+		echo "All Regression test passed!"; \
+	fi; \
+	echo ""
 
 #可以先跑一遍拿到diff的返回值，再把有错的对比打出来
 #diff $$test.out $$test.gold 2>&1 > /dev/null; \
 #diff $$test.gold $$test.out > $$test.err; \
+
+MY_TESTS_DATA=wupdata-1.hdf wupdata-2.hdf
+test_my:
+	@echo "Running wup cs tests"
+	@cd ../../../resource/; \
+	failed=0;\
+	for wupdata in $(MY_TESTS_DATA); do \
+		node test.js $$wupdata cs/wupmain.cs > $$wupdata.out.html; \
+		diff $$wupdata.out.html $$wupdata.gold.html > $$wupdata.diff; \
+		return_code=$$?; \
+		if [ $$return_code -ne 0 ]; then \
+			echo "$$wupdata" test failed!; \
+			failed=1; \
+		else \
+			rm -rf $$wupdata.out.html; \
+			rm -rf $$wupdata.diff; \
+		fi; \
+	done; \
+	if [ $$failed -eq 1 ]; then \
+		echo "Test wupdata Failed!"; \
+	else \
+		echo "All wupdata test passed!"; \
+	fi;
